

# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [87]:
# 1. Import the numpy package under the name np (★☆☆)

import numpy as np

In [88]:
#2. Create a null vector of size 10 (★☆☆)

a = np.zeros((10))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [89]:
#3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)¶

a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [90]:
#4. Create a vector with values ranging from 10 to 49 (★☆☆)¶

np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [91]:
#5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

b = np.arange(0, 9).reshape((3, 3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [92]:
#6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

c = np.array([1,2,0,0,4,0])
np.nonzero(c)

(array([0, 1, 4]),)

In [93]:
#7. Create a 3x3 identity matrix (★☆☆)

d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [94]:
#8. Create a 3x3x3 array with random values (★☆☆)


np.random.random((3,3))

array([[0.2247385 , 0.88159073, 0.43972231],
       [0.93307084, 0.51235773, 0.98250396],
       [0.99953956, 0.50949975, 0.50245559]])

In [95]:
#9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

f=np.random.random((10,10))
print(f)

[[0.58626925 0.58940149 0.61630204 0.81273097 0.68960533 0.03070382
  0.86700487 0.75562235 0.24594475 0.05672803]
 [0.32713517 0.13029346 0.50220504 0.15836022 0.91721191 0.71406361
  0.15048171 0.32545551 0.33365686 0.73891452]
 [0.27662326 0.45062456 0.3732473  0.18150829 0.71850959 0.32560585
  0.61915735 0.7779     0.29520974 0.8092637 ]
 [0.35955216 0.97930026 0.83542275 0.899419   0.74210405 0.2448005
  0.42388545 0.74691822 0.89570327 0.49041849]
 [0.71053313 0.77767942 0.1251745  0.49468151 0.44326245 0.88674899
  0.03228709 0.61254817 0.91167181 0.08928335]
 [0.93165174 0.95956609 0.10828029 0.71057478 0.70329448 0.656227
  0.45605142 0.19692273 0.63762914 0.19779594]
 [0.795131   0.91071272 0.92032627 0.65245169 0.94971283 0.91236011
  0.49213567 0.01221767 0.44508516 0.47016907]
 [0.73963587 0.39574449 0.31705125 0.32372505 0.64630876 0.87630767
  0.83872523 0.81752343 0.8438311  0.42628354]
 [0.62546589 0.93421989 0.73504633 0.18188711 0.65889428 0.71371102
  0.22596055 0.

In [96]:
#10. Create a random vector of size 30 and find the mean value (★☆☆)

np.amax(f)


0.9940104275301752

In [33]:
np.amin(f)

0.002020998540269381

In [97]:
#11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


g = np.random.random(30)
print(g)

[0.80174743 0.54237976 0.26431801 0.08211276 0.5926734  0.66382764
 0.00303369 0.02947761 0.53773883 0.36104997 0.31995177 0.77380433
 0.26734028 0.98393813 0.19420979 0.50806853 0.98243226 0.04432016
 0.476967   0.48728961 0.75123847 0.69121045 0.5249373  0.730539
 0.97405536 0.64366184 0.22354394 0.86624204 0.7299421  0.34511672]


In [101]:
np.mean(g)

0.5132389393453541

In [102]:
h = np.arange(0,26)
i = np.arange(0, 25).reshape((5, 5))
print(i)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [49]:
i[1,0]=1
i[2,1]=2
i[3,2]=3
i[4,3]=4
print(i)

[[ 0  1  2  3  4]
 [ 1  6  7  8  9]
 [10  2 12 13 14]
 [15 16  3 18 19]
 [20 21 22  4 24]]


In [103]:
#12. Normalize a 5x5 random matrix (★☆☆)

l = np.random.random(25)
m = np.random.random(25).reshape((5, 5))
print(m)

[[0.61084673 0.55014322 0.66622187 0.37674017 0.87240754]
 [0.08203236 0.39053927 0.0728521  0.08926246 0.661474  ]
 [0.95837745 0.71259019 0.18141821 0.3836102  0.68197181]
 [0.10766065 0.1940795  0.86923823 0.39796569 0.75752503]
 [0.03496755 0.52276759 0.66893013 0.23815234 0.75674556]]


In [105]:
z = (m[0:5] - np.mean(m[0:5])) / (np.std(m[0:5]))
print(z)

[[ 0.48708925  0.27174512  0.68353113 -0.3433977   1.41496942]
 [-1.38886603 -0.29444577 -1.42143275 -1.36321741  0.66668817]
 [ 1.71994548  0.84802152 -1.03629731 -0.31902644  0.73940361]
 [-1.29795031 -0.99138168  1.40372639 -0.26810073  1.0074267 ]
 [-1.5558272   0.17463078  0.6931386  -0.83503442  1.00466157]]


In [100]:
#13. How to find common values between two arrays? (★☆☆)

o = np.arange(0,20)
p = np.arange(10,30)
n = np.intersect1d(o,p)
print(n)

[10 11 12 13 14 15 16 17 18 19]


In [106]:
#14. Create a random vector of size 10 and sort it (★★☆)

q = np.random.random(10)
np.sort(q)


array([0.07678143, 0.14442142, 0.23606314, 0.2472639 , 0.30153306,
       0.3136412 , 0.46702577, 0.7672384 , 0.83460694, 0.84081755])

In [107]:
#15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)¶

r = np.random.random(10)
print(r)

[0.13760508 0.69239192 0.87724058 0.00133933 0.7299572  0.38109499
 0.15195169 0.44278981 0.11753909 0.31333389]


In [71]:
np.argmax(r)

5

In [72]:
r[5]=0

In [73]:
print(r)

[0.38731823 0.34930209 0.54597729 0.62707478 0.73068364 0.
 0.84470467 0.16186429 0.19988836 0.79096548]


In [108]:
#16. Subtract the mean of each row of a matrix (★★☆)


s = np.random.random((5,5))
print(s)

print("\nSubtract the mean of each row of the matrix:\n")
t = s - s.mean(axis=1, keepdims=True)
print(t)


[[0.8500937  0.793726   0.25571722 0.86084992 0.1462727 ]
 [0.17290986 0.13124866 0.2816039  0.33851909 0.61077873]
 [0.43287    0.91599908 0.85032908 0.73771356 0.10413392]
 [0.21304082 0.37202443 0.70101351 0.68642871 0.89180283]
 [0.91569049 0.11067242 0.59510921 0.11303795 0.87145234]]

Subtract the mean of each row of the matrix:

[[ 0.26876179  0.21239409 -0.32561469  0.27951801 -0.43505921]
 [-0.13410219 -0.17576339 -0.02540815  0.03150704  0.30376668]
 [-0.17533913  0.30778996  0.24211995  0.12950443 -0.50407521]
 [-0.35982124 -0.20083764  0.12815145  0.11356665  0.31894077]
 [ 0.39449801 -0.41052006  0.07391673 -0.40815453  0.35025986]]


In [120]:
#### 17. How to get the n largest values of an array (★★★)

u = np.arange(50)
np.random.shuffle(u)
np.argsort(u)


array([ 5,  4, 49, 13, 42,  3, 38, 28, 29, 47, 25, 27, 35, 15,  2, 40, 23,
       30, 33, 46, 10, 26, 31,  6, 16, 21, 32,  7, 36,  1, 20,  8, 14, 44,
        9, 34, 12, 18, 43, 45,  0, 41, 37, 19, 48, 22, 39, 11, 24, 17])

In [121]:
np.argpartition(u, -5)[-5:]

array([22, 39, 11, 24, 17])

In [147]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

v = np.random.randint(0,15,15)
j = np.random.randint(0,15,15).reshape((5, 3))
print(j)


[[14  3  9]
 [ 6  1 10]
 [ 3  2  3]
 [10  9  9]
 [ 0 13 14]]


In [155]:
print(np.where(j > 4, j**2, j))


[[196   3  81]
 [ 36   1 100]
 [  3   2   3]
 [100  81  81]
 [  0 169 196]]
